// <auto-generated />
using DEU_Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DEU_Backend.Migrations
{
    [DbContext(typeof(DeuDbContext))]
    partial class DeuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DEU_Lib.Model.WaKaWaterSource", b =>
                {
                    b.Property<int>("WaKaWaterSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Connections")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Flowrate")
                        .HasColumnType("INTEGER");

                    b.Property<double>("IconAnchorX")
                        .HasColumnType("REAL");

                    b.Property<double>("IconAnchorY")
                        .HasColumnType("REAL");

                    b.Property<double>("IconHeight")
                        .HasColumnType("REAL");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<double>("IconWidth")
                        .HasColumnType("REAL");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceWaKaWaterSourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WaKaWaterSourceId");

                    b.ToTable("WaKaWaterSources");
                });
#pragma warning restore 612, 618
        }
    }
}
